{% set name = "lenstool" %}
{% set version = "8.13.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://git-cral.univ-lyon1.fr/{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7179bb9a75362523ea36ba25800e44b74ddadd587832e444b505cba93ff85d49

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [not win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [not win]
    - m2-bash  # [win]
    - m2-make  # [win]
    - pkg-config
    - autoconf  # [not win]
    - automake  # [not win]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python
    - pip
    - setuptools
    - cfitsio
    - wcslib  # [not win]
    - gsl
    - libblas  # [linux]
    - astropy-base
  run:
    - python
    - numpy
    - cfitsio
    - wcslib  # [not win]
    - gsl
    - libblas  # [linux]
    - astropy-base
    - scipy
    - emcee
    - matplotlib-base
    - corner

test:
  imports:
    - lenstool

  commands:
    - test -f $PREFIX/bin/lenstool  # [unix]

about:
  home: https://projets.lam.fr/projects/lenstool
  license: GPL-3.0-only
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: A gravitational lensing software for modeling mass distribution of galaxies and clusters (strong and weak regime).

extra:
  recipe-maintainers:
    - ejullo
    - njzifjoiez
