{% set name = "lenstool" %}
{% set version = "8.14.2" %}


package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://git-cral.univ-lyon1.fr/{{ name }}/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: e64476e48b85c7eb45bf940a5a36954e1310239426da91ed03f56b6b18fc291a

build:
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - libtool  # [not win]
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - autotools_clang_conda  # [win]
    - make  # [not win]
    - m2-bash  # [win]
    - m2-coreutils  # [win]
    - m2-diffutils  # [win]
    - m2-findutils  # [win]
    - m2-gawk  # [win]
    - m2-grep  # [win]
    - m2-make  # [win]
    - m2-sed  # [win]
    - m2-which  # [win]
    - pkg-config
    - autoconf  # [not win]
    - automake  # [not win]
  host:
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
    - python
    - pip
    - setuptools
    - cfitsio
    - pthreads-win32  # [win]
    - wcslib  # [not win]
    - gsl
    - libblas  # [linux]
    - astropy-base
  run:
    - python
    - numpy
    - cfitsio
    - wcslib  # [not win]
    - gsl
    - libblas  # [linux]
    - astropy-base
    - scipy
    - emcee
    - matplotlib-base
    - corner

test:
  imports:
    - lenstool

  commands:
    - test -f $PREFIX/bin/lenstool  # [unix]

about:
  home: https://projets.lam.fr/projects/lenstool
  license: GPL-3.0-only
  license_file: {{ RECIPE_DIR }}/LICENSE
  summary: A gravitational lensing software for modeling mass distribution of galaxies and clusters (strong and weak regime).

extra:
  recipe-maintainers:
    - ejullo
    - njzifjoiez
